### ISSUE TITLE
Support for tracing

### ISSUE THREAD

**Issue by kellytk** [bastion-rs/bastion#102]
**Describe the solution you'd like**
Could `bastion` be improved by adding support for tracing?

Related crates: https://github.com/anelson/tracers, https://github.com/tokio-rs/tracing

Related issues: https://github.com/bastion-rs/bastion/issues/2, https://github.com/bastion-rs/bastion/issues/77

**Comment by vertexclique** [comment]
We need to bikeshed for a possible solution to this. We need to take a closer look at tokio's tracing and check dependencies. Based on that we can include it or not. Seems like that's the one widely used around.

**Comment by vertexclique** [comment]
@bastion-rs/coredev what are you thoughts about this?

**Comment by attliaLin** [comment]
I'd like to take it.

**Comment by vertexclique** [comment]
@attliaLin Feel free to take it. Assigned on you. If you need further info we can provide it.
