### ISSUE TITLE
Add a "spawn" method to "Bastion"

### ISSUE THREAD

**Issue by azastrael** [bastion-rs/bastion#116]
**Describe the solution you'd like**
Add a `spawn` method to `Bastion` that would roughly translate to `Bastion::children(|ch| ch.with_exec(_));`.

**Comment by Stupremee** [comment]
Can I take care of this issue?

**Comment by azastrael** [comment]
@Stupremee most definitely ;)

I assigned the issue to you, don’t hesitate to tell me if you need some help (here or in Discord) :)

**Comment by vertexclique** [comment]
Thanks @Stupremee . Merged, we can close this now.
