### ISSUE TITLE
Migrate and groom all issues to have a Rust Lang like issue tagging

### ISSUE THREAD

**Issue by vertexclique** [bastion-rs/bastion#138]
Hi all;

Currently, we are tagging issues with basic `research`, `support`, `help-wanted` like how GitHub suggests. For the people who have just started to contribute and/or for us sometimes it is really hard to pick and find the items related to an issue.

So here comes the proposal for issue tagging layout.
Which is diagonal to both bug, feature request and components:
* A-routing: Area: Routing component's issues
    * Other examples: A-children, A-callbacks, A-supervisor etc.
* C-feature-request: Category: Feature Request
    * Other examples: C-feature-compat, C-bug etc.
* D-general: Diagnostics: General level
    * Other examples: D-incorrect, D-inconsistent
* I-executor: Internals: Executor (yes I know that' not very Rust lang style but why not?)
    * Other examples: I-lightproc, I-scheduler, I-run-queues etc.

Please feel free to extend or suggest to the layout and give feedback.

here is a [cat](https://media.giphy.com/media/CjmvTCZf2U3p09Cn0h/giphy.gif)!

**Comment by Stupremee** [comment]
What about a status tag to represent the status of the issue.

**Comment by vertexclique** [comment]
What do you mean? Assignee, is it free or not, or deferred or going to be done?

**Comment by Stupremee** [comment]
yep, e.g. `assigned`, `needs-change`, `done` / `finished`, `ready-to-implement`.

**Comment by vertexclique** [comment]
`assigned` can be filtered by Github UI.
`done` is determined by the PR closing. If we write `Fixes #issuenr` it will be closed.
Lack of `ready-to-implement` shouldn't necessarily need someone to stop doing it.
`finished` is basically the same as `done` case.

**Comment by vertexclique** [comment]
New labels are added. Let's groom the issues.
