### ISSUE TITLE
Preserve mailbox on child respawn

### ISSUE THREAD

**Issue by onsails** [bastion-rs/bastion#139]
Currently on a child failure children will spawn another child. Previous child's mailbox will be disposed. It doesn't fit into let-it-fail concept.

We need `child`s to preserve mailbox on respawn. Also we need a lifecycle callbacks which can access child state and a message which caused child failure.

**Comment by vertexclique** [comment]
Like we have talked, let's go with flat hierarchy for this.

**Comment by untoldbyte** [comment]
if it is of any help. I started looking outside of actix cause it doesnt support this. its very important to have this to truly mimic the fautl tolerance of BEAM

I speak this as an end-user and not a developer

**Comment by Relrin** [comment]
Done in PR #199.
