### ISSUE TITLE
Bastion will busy-loop consuming 100% of one CPU

### ISSUE THREAD

**Issue by rtyler** [bastion-rs/bastion#148]
* **Version**: 0.3.1
* **Platform**: Linux/amd64
* **Subsystem**:

The snippet below will cause a CPU-intensive busyloop, which results in a CPU being occupied by an otherwise idle process. I would expect that the program below should instead have practically zero overhead

```rust
use bastion::prelude::*;

fn main() {
    println!("Starting to spin...check top(1)");
    Bastion::init();
    Bastion::start();
    Bastion::block_until_stopped();
}
```

The pull request #147 represents the first part of the work, but does not completely address the issue

**Comment by vertexclique** [comment]
Fixed by #147
