### ISSUE TITLE
Documentation request: Hello world for distributed operation

### ISSUE THREAD

**Issue by rw** [bastion-rs/bastion#166]
Could we make a Hello World example of how to do multi-server distributed operation in Bastion? It would be helpful to folks like me who are evaluating Bastion for an Erlang-style use case.

Thank you!

**Comment by vertexclique** [comment]
As soon as possible we will make this available. Please bear with us.

**Comment by vertexclique** [comment]
Hi @rw as promised you can find an example here:
https://github.com/bastion-rs/showcase/blob/master/bastion-cluster/src/main.rs

This example forms a Bastion Cluster that enables message passing between distributed actors.
Received remote messages can be replicated and destined to local actors and enable further processing.

Thanks for bearing with us!
