### ISSUE TITLE
Update the bastion graph

### ISSUE THREAD

**Issue by o0Ignition0o** [bastion-rs/bastion#215]
Maybe as a followup to #192 we could try to update the [bastion arch picture](https://github.com/bastion-rs/bastion/blob/master/img/bastion-arch.png).

It would allow us to put it back on the readme and it would look better on the website :)

**Comment by creativcoder** [comment]
Hey @o0Ignition0o assign me! Post this, I would also like to work on #189

**Comment by o0Ignition0o** [comment]
Amazing! thanks a lot for doing this!

**Comment by fosdickio** [comment]
@o0Ignition0o Will you assign me for this one and review?  I opened up PR #311 to address this issue.

**Comment by vertexclique** [comment]
#311 is merged, closing this one. Thanks again!
