### ISSUE TITLE
Dispatcher example

### ISSUE THREAD

**Issue by o0Ignition0o** [bastion-rs/bastion#216]
It might be hard at first to figure out how children work and how to send messages to them.

A common pattern is round robin dispatch, so it would be great to have such an example:

Spawn 5 children
Create a dispatcher

Send several messages to the group, and watch them go to each child in turn

**Comment by oScape** [comment]
I would love to take it. It might be interesting for me to learn more about children/message.

**Comment by o0Ignition0o** [comment]
Amazing, go for it ! :rocket:
