### ISSUE TITLE
Use futures::future::Abortable to implement global Kill strategies

### ISSUE THREAD

**Issue by vertexclique** [bastion-rs/bastion#22]
Replace all future spawn principles to use:
https://docs.rs/futures-preview/0.3.0-alpha.18/futures/future/struct.Abortable.html

That will make the system hook much more reliable. Because we won't wait for exiting from the future if we want to kill a future.

**Comment by vertexclique** [comment]
This is also tied to `async-task` implementation. Not high-prio right now will wait for the stable release from that side.

**Comment by vertexclique** [comment]
We need to think about this that do we still need this after the redesign.

**Comment by azastrael** [comment]
@vertexclique isn't it what `ProcHandle::cancel` and `RecoverableHandle::cancel` do?

**Comment by vertexclique** [comment]
Yes, definitely. So we can close this.
