### ISSUE TITLE
100% CPU usage (sometimes)

### ISSUE THREAD

**Issue by pietgeursen** [bastion-rs/bastion#243]
* **Version**: 0.4.0
* **Platform**: Linux  5.7.7-arch1-1 #1 SMP PREEMPT Wed, 01 Jul 2020 14:53:16 +0000 x86_64 GNU/Linux
* **Subsystem**: ?
* **Rust**: rustc 1.45.0

I see similar behaviour as #109. If I run a simple bastion program, ~50% of the runs one of my cpus goes to 100%

I can reproduce this with something as simple as: 

```rs
fn main() {
    let config = Config::new().hide_backtraces();
    Bastion::init_with(config);
    Bastion::start();
    Bastion::block_until_stopped();
}
```

**Comment by o0Ignition0o** [comment]
Hey, that's an interesting one, I'll try to reproduce it!

**Comment by o0Ignition0o** [comment]
I need to dig deeper with a profiler, but I just ran into a lot of allocations / resizes in the hot path while profiling something else, #260 may or may not have an impact here ^^

**Comment by o0Ignition0o** [comment]
```     6.15%  bastion-async-t  weird             [.] _ZN100_$LT$bastion_executor..load_balancer..Stats$u20$as$u20$bastion_executor..load_balancer..SmpStats$GT$15get_sorted_load17h8ce4900e67fbd3a7E
     5.03%  bastion-async-t  weird             [.] _ZN99_$LT$core..iter..adapters..Enumerate$LT$I$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h4df0d33504e02321E
     4.86%  bastion-async-t  weird             [.] _ZN85_$LT$core..slice..Iter$LT$T$GT$$u20$as$u20$core..iter..traits..iterator..Iterator$GT$4next17h7c6ba6c4ca7d97bfE
     4.12%  bastion-async-t  weird             [.] _ZN5alloc5slice10merge_sort17heb79efdfbfab3bedE
     3.92%  bastion-async-t  weird             [.] _ZN5alloc5slice11insert_head17hf6717e21221c8cabE
     3.63%  bastion-async-t  weird             [.] _ZN4core4sync6atomic11atomic_load17he0b9c62d2c6d7ceaE```

So I've been able to reproduce it, and I'm working on it through #261 261

**Comment by o0Ignition0o** [comment]
![image](https://user-images.githubusercontent.com/9465678/90076079-22fd0580-dcff-11ea-9161-7c0e535267a4.png)

Ok I think it starts looking good!

@anlumo @pietgeursen could you please give it an other try targeting `igni/affine_steal_sort` on bastion and bastion-executor ? 🙏

**Comment by pietgeursen** [comment]
Nice one @o0Ignition0o! 

I tried out that branch and it seems to fix it. My testing is _super_ basic, I'm just starting and stopping the program a bunch and checking the cpu usage. But cpu usage always stays low.

**Comment by o0Ignition0o** [comment]
Amazing news! There's still a couple of tweaks I'm trying to perform, but it will definitely have a good impact for everyone, thanks a lot for raising this issue!
