### ISSUE TITLE
documentation: Bastion

### ISSUE THREAD

**Issue by o0Ignition0o** [bastion-rs/bastion#246]
In the [Bastion struct documentation example](https://docs.rs/bastion/0.4.0/bastion/struct.Bastion.html), there's an `await` call in a non async function (main).

We might want to create an async function to [run!](https://github.com/bastion-rs/bastion/blob/master/src/bastion/examples/fibonacci.rs#L111) this instead!

I would be happy to mentor anyone on this doc issue, feel free to reply with questions, or just comment "assign me!" and the bug is yours :D

**Comment by creativcoder** [comment]
assign-me!

**Comment by o0Ignition0o** [comment]
Amazing, just assigned you! Feel free to ask any question, I'd be happy to help!

**Comment by o0Ignition0o** [comment]
fixed through #250 , thanks for doing this!

Please reach out to me if you wanna try an other one :)
