### ISSUE TITLE
recv_timeout

### ISSUE THREAD

**Issue by anlumo** [bastion-rs/bastion#251]
**Is your feature request related to a problem? Please describe.**

In BastionContext, there's `recv` and `try_recv`. The API I'm using requires that I send a 30Hz heartbeat when no message is received, and both of these can't do that.

**Describe the solution you'd like**

A `recv_timeout` like in [std::sync::mpsc::Receiver](https://doc.rust-lang.org/std/sync/mpsc/struct.Receiver.html#method.recv_timeout) would be great. If a message is received, schedule the child immediately to process it. If no message arrives until the timeout, schedule the child with a `None` value.

**Describe alternatives you've considered**

I could add a heartbeat task that sends a message 30 times a second, but that adds a lot of overhead and can't handle situations properly where other messages are received by the target (because the heartbeat task can't know about them).

Alternatively, I could use something like the [timed function of the async_timer](https://docs.rs/async-timer/1.0.0-beta.5/async_timer/fn.timed.html) crate, but it'd be better if this would be integrated with bastion.

**Comment by o0Ignition0o** [comment]
I think it was fixed through #253
