### ISSUE TITLE
Miri flag passing changed

### ISSUE THREAD

**Issue by RalfJung** [bastion-rs/bastion#274]
`cargo miri test` changed to be more compatible with `cargo test`, but this means we had to find a different way to pass flags to the interpreter, so there now is a `MIRIFLAGS` environment variable for that. The old way still works for now, but is deprecated. To remain compatible, would be great if you could update `cargo miri test --features lever/nightly -- -Zmiri-disable-isolation -Zmiri-ignore-leaks -- dispatcher` (etc) to `MIRIFLAGS="-Zmiri-disable-isolation -Zmiri-ignore-leaks" cargo miri test --features lever/nightly dispatcher`.

**Comment by o0Ignition0o** [comment]
Hey there, thanks a lot for letting us know! :)
