### ISSUE TITLE
Doc links

### ISSUE THREAD

**Issue by o0Ignition0o** [bastion-rs/bastion#280]
Quite a bit of doc links are out of date, refering to the old location of files. this calls for a pass to check what happened and what is where now 

* **Version**:
* **Platform**:
* **Subsystem**:

**Comment by scrabsha** [comment]
I'll work on this one! Additionally, I'll migrate every link I find to the new intra-doc-link.

**Comment by o0Ignition0o** [comment]
That's amazing, thanks for doing this! 🎉

**Comment by scrabsha** [comment]
I have nearly fixed everything.

I'm wondering what should be done [here][weird-link]: should we redirect to [`RefAddr`] or to [`Answer`].

[weird-link]: https://github.com/bastion-rs/bastion/blob/0d159ea4839e5aeb29f8bd1e9b7400556288230b/src/bastion/src/context.rs#L577
[`RefAddr`]: https://docs.rs/bastion/0.4.4/bastion/envelope/struct.RefAddr.html
[`Answer`]: https://docs.rs/bastion/0.4.4/bastion/message/struct.Answer.html

**Comment by o0Ignition0o** [comment]
Haha good question 😂 

I would point to `RefAddr`, and I think we can rework the docs later, to add more intent as to what we mean by "signature, sender, receiver" etc.

But I guess this will make more sense once #309 lands :D

**Comment by scrabsha** [comment]
One last question:
The documentation for `BastionContext` has a link entitled [`exec`]. I searched across the codebase, but found no function with that name. What am I missing?

[`exec`]: https://github.com/bastion-rs/bastion/blob/0d159ea4839e5aeb29f8bd1e9b7400556288230b/src/bastion/src/context.rs#L77

**Comment by o0Ignition0o** [comment]
Entitled links, I hate them :p 

i think it refers to a child’s with exec closure,that is executed on each spawn: 
https://github.com/bastion-rs/bastion/blob/master/src/bastion/src/child.rs#L423

https://github.com/bastion-rs/bastion/blob/master/src/bastion/src/children.rs#L306

Maybe ?

sorry I’m on the phone I can’t format it better :/
