### ISSUE TITLE
Seems odd to warn about this

### ISSUE THREAD

**Issue by marshray** [bastion-rs/bastion#307]
Looks like normal operation. Possibly leftover dev code?

https://github.com/bastion-rs/bastion/blob/0d159ea4839e5aeb29f8bd1e9b7400556288230b/src/bastion/src/dispatcher.rs#L95

**Comment by o0Ignition0o** [comment]
Hey!

good catch! It seems to be a leftover from when we debugged the broadcast targets, I think it should be trace!

**Comment by vertexclique** [comment]
Lowered to debug, before the next release these are going to be trace.
