### ISSUE TITLE
Reword README.md (for all workspace projects)

### ISSUE THREAD

**Issue by vertexclique** [bastion-rs/bastion#61]
Reword README so people should understand what Bastion does and what is the point of it.

**Comment by yavrib** [comment]
Reword as in rephrase everything/whatever is necessary?

**Comment by azastrael** [comment]
@yavrib I'll let @vertexclique answer that, but for the **Getting Started**, the example used in `bastion::Bastion`should probably be used.

**Comment by vertexclique** [comment]
> Reword as in rephrase everything/whatever is necessary?

Yes. Main things are:
- [ ] the small storylike entry in readme
- [ ] rewording what project does (I've rewritten the main doc header, you can take a look – https://github.com/bastion-rs/bastion/blob/master/bastion/src/lib.rs#L6)
- [ ] Writing README for `bastion-executor` and `lightproc`.
- [ ] In main README using the example used in `bastion::Bastion` should be used. (https://github.com/bastion-rs/bastion/blob/master/bastion/src/bastion.rs#L15)

**Comment by vertexclique** [comment]
This is done. Let's close this one.
