### ISSUE TITLE
Community-related files

### ISSUE THREAD

**Issue by azastrael** [bastion-rs/bastion#73]
Hey :wave:!

It would be nice if we had:
- [x] [guidelines for new contributors](https://help.github.com/en/github/building-a-strong-community/setting-guidelines-for-repository-contributors)
- [x] a [code of conduct](https://help.github.com/en/github/building-a-strong-community/adding-a-code-of-conduct-to-your-project)
- [x] [support resources](https://help.github.com/en/github/building-a-strong-community/adding-support-resources-to-your-project)

**Comment by JohnTitor** [comment]
I think it'd be nice that we have their documentation for all repo under bastion-rs so we should create `.github` repo and put them there?

**Comment by JohnTitor** [comment]
One minor question: what should we document with the support resources?
I'm not familiar with that so I don't come up with the content.

**Comment by vertexclique** [comment]
Including:
* StackOverflow on the readme of the project
* Discord server invite.
* Asking questions tagged as `question` and putting this choice under (https://github.com/bastion-rs/bastion/issues/new/choose) maybe will be good.

**Comment by JohnTitor** [comment]
This can be closed?
